language: node_js
sudo: true
cache:
  directories:
    - node
    - node_modules

dist: trusty

node_js:
  - '6.9.2'

addons:
  apt:
    packages:
      - libopencv-dev # Install Dependencies

branches:
  only:
  - master
  - develop

before_install:
 - sudo apt-get update
 - which yarn
 - npm install -g yarn

script:
 - npm rebuild opencv
 - yarn test

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


